{% set name = "dotdict" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dotdict-{{ version }}.tar.gz
  sha256: 2ac71d4c1e2c46ccb0f79fd0d375676b70c597a25375ca8d4c095cb04656b75b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm
  run:
    - python >=3.7

test:
  imports:
    - dotdict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nicholasmireles/DotDict
  summary: Dot style dictionary like JavaScript.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
